services:
  - type: web
    name: web-application-2025-group-9
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --workers 1 --timeout 120 --preload
    preDeployCommand: flask db upgrade
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: BIZZY_API_KEY
        sync: false
